import ClientWrapper from '../../components/ClientWrapper';
import SidebarWrapper from './SideBarWrapper';
import Toolbox from './toolbox';


export const metadata = {
  title: 'Naxiora',
  manifest: '/manifest.json',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="textfont">
        <ClientWrapper>
          <div style={{ display: 'flex', height: '100vh' }}>
            <div className="h-screen flex items-center ml-5 justify-center">
              <SidebarWrapper />
            </div>

            <main className="flex-1 p-2 h-[100vh] flex flex-col">
              <div className="bg-[none] px-6 flex items-center justify-between h-20">
                <div className="flex items-center space-x-2">
                  <h1 className="textcolor text-2xl font-semibold">Good Morning,</h1>
                  <div>
                    <span className="textcolor text-2xl font-bold">John Doe</span>
                  </div>
                </div>
                <div className="flex items-center justify-center">
                  <Toolbox />
                </div>
              </div>

              <div className="flex-1 overflow-auto ml-4 mr-4">
                {children}
              </div>
            </main>
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}
