import { Archivo } from 'next/font/google';
import './globals.css';
import ClientWrapper from '../components/ClientWrapper';

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-archivo',
});

export const metadata = {
  title: 'Create Next App',
  manifest: '/manifest.json',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={archivo.variable}>
      <body>
        <ClientWrapper>
        {children}
        </ClientWrapper>
        </body>
    </html>
  );
}