
import './globals.css';
import ClientWrapper from '../components/ClientWrapper';



export const metadata = {
  title: 'Naxiora',
  manifest: '/manifest.json',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
        {children}
        </ClientWrapper>
        </body>
    </html>
  );
}